name: Continuous Delivery

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hive-box:${{ github.sha }}
            ghcr.io/${{ github.repository }}/hive-box:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Manifests to S3
        run: |
          aws s3 sync k8s s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Apply Kubernetes Manifests
        run: |
          for file in $(aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive | awk '{print $4}'); do
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/$file $file
            kubectl apply -f $file
          done
