name: Continuous Delivery

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v1"
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hive-box:${{ github.sha }}
            ghcr.io/${{ github.repository }}/hive-box:latest
