name: Hive Box CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint Python code
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Build Docker image
        run: docker build -t hive-box .

      - name: Run Unit Tests
        run: docker run hive-box python -m unittest discover -s tests

  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          results_format: json
