name: Hive Box Scorecard
on:
  pull_request:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.json
