name: Docker With Tests
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hive-box .

      - name: Run Unit Tests
        env:
          SENSEBOX_API_URL: ${{ secrets.SENSEBOX_API_URL }}
        run: docker run -e SENSEBOX_API_URL=${{ secrets.SENSEBOX_API_URL }} hive-box python -m unittest discover -s tests
